/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    UAnchor: typeof import('undraw-ui')['UAnchor']
    UChat: typeof import('undraw-ui')['UChat']
    UComment: typeof import('undraw-ui')['UComment']
    UCommentNav: typeof import('undraw-ui')['UCommentNav']
    UCommentScroll: typeof import('undraw-ui')['UCommentScroll']
    UCounter: typeof import('undraw-ui')['UCounter']
    UDialog: typeof import('undraw-ui')['UDialog']
    UDivider: typeof import('undraw-ui')['UDivider']
    UEditor: typeof import('undraw-ui')['UEditor']
    UFold: typeof import('undraw-ui')['UFold']
    UIcon: typeof import('undraw-ui')['UIcon']
    UNoticeBar: typeof import('undraw-ui')['UNoticeBar']
    USearch: typeof import('undraw-ui')['USearch']
    USign: typeof import('undraw-ui')['USign']
    UTags: typeof import('undraw-ui')['UTags']
  }
}
