<template>
  <div class="search">
    <div class="icon">
      <u-icon class="cursor-pointer" @click="searchBtn"><Search /></u-icon>
    </div>
    <div class="input-box" :class="{ show: show }">
      <u-search2 ref="searchRef" v-model="keyword" @remote-search="remoteSearch" @select="select" @blur="show=false"></u-search2>
    </div>
  </div>
</template>
<script setup lang="ts">
import { isEmpty } from 'undraw-ui'
import { nextTick, ref } from 'vue'
import { Search } from '@element-plus/icons-vue'

const show = ref(false)

const keyword = ref('')
const searchRef = ref()

const menu = [
  {
    id: 63,
    parentId: 41,
    path: '/erp/update',
    type: 1,
    orderNum: 0,
    title: 'erp修改',
    icon: 'lightning',
    anonymous: false,
    name: null,
    component: null,
    keepAlive: false,
    outLink: null,
    createTime: '2024-03-28 09:26:52',
    updateTime: '2024-03-28 09:26:52',
    roles: null
  },
  {
    id: 93,
    parentId: 92,
    path: '/erp/warehouse',
    type: 2,
    orderNum: 0,
    title: '仓库报表',
    icon: 'find',
    anonymous: false,
    name: '',
    component: '/src/views/system/iframe/index.vue',
    keepAlive: false,
    outLink: 'http://180.100.207.79:6080/ERPReportSet/home',
    createTime: '2025-02-20 17:13:58',
    updateTime: '2025-02-20 17:13:58',
    roles: null
  },
  {
    id: 92,
    parentId: 41,
    path: '/erp/report',
    type: 1,
    orderNum: 0,
    title: '报表',
    icon: 'analysis',
    anonymous: false,
    name: null,
    component: null,
    keepAlive: false,
    outLink: null,
    createTime: '2025-02-11 09:31:16',
    updateTime: '2025-02-20 16:39:23',
    roles: null
  },
  {
    id: 10,
    parentId: 21,
    path: '/menu/list',
    type: 3,
    orderNum: 1,
    title: '查询所有菜单列表',
    icon: null,
    anonymous: false,
    name: null,
    component: null,
    keepAlive: false,
    outLink: null,
    createTime: '2023-05-24 09:16:14',
    updateTime: '2023-05-24 09:16:14',
    roles: null
  },
  {
    id: 19,
    parentId: 18,
    path: '/system/auth/user',
    type: 2,
    orderNum: 1,
    title: '用户管理',
    icon: 'user',
    anonymous: false,
    name: 'user',
    component: '/src/views/system/auth/user/index.vue',
    keepAlive: true,
    outLink: null,
    createTime: '2023-05-24 09:16:14',
    updateTime: '2023-05-24 09:16:14',
    roles: null
  },
  {
    id: 18,
    parentId: 17,
    path: '/system/auth',
    type: 1,
    orderNum: 1,
    title: '权限管理',
    icon: 'lock',
    anonymous: false,
    name: null,
    component: null,
    keepAlive: false,
    outLink: null,
    createTime: '2023-05-24 09:16:14',
    updateTime: '2023-05-24 09:16:14',
    roles: null
  },
  {
    id: 23,
    parentId: 22,
    path: '/system/monitor/system-log',
    type: 2,
    orderNum: 1,
    title: '请求日志',
    icon: 'log',
    anonymous: false,
    name: 'system-log',
    component: '/src/views/system/monitor/system-log/index.vue',
    keepAlive: false,
    outLink: null,
    createTime: '2023-05-24 09:16:14',
    updateTime: '2023-05-24 09:16:14',
    roles: null
  },
  {
    id: 24,
    parentId: null,
    path: '/home',
    type: 2,
    orderNum: 1,
    title: '首页',
    icon: 'home',
    anonymous: false,
    name: 'home',
    component: '/src/views/home/index.vue',
    keepAlive: false,
    outLink: null,
    createTime: '2023-05-24 09:16:14',
    updateTime: '2023-05-24 09:16:14',
    roles: null
  },
  {
    id: 26,
    parentId: 25,
    path: '/visualizing/share',
    type: 2,
    orderNum: 1,
    title: '数据可视化演示',
    icon: 'share',
    anonymous: false,
    name: 'share',
    component: '/src/views/visualizing/index.vue',
    keepAlive: false,
    outLink: null,
    createTime: '2023-05-24 09:16:14',
    updateTime: '2023-05-24 09:16:14',
    roles: null
  },
  {
    id: 31,
    parentId: 20,
    path: '/role/list',
    type: 3,
    orderNum: 1,
    title: '查询所有角色列表',
    icon: null,
    anonymous: false,
    name: null,
    component: null,
    keepAlive: false,
    outLink: null,
    createTime: '2023-08-26 10:31:16',
    updateTime: '2023-08-26 10:31:16',
    roles: null
  },
  {
    id: 53,
    parentId: 63,
    path: '/erp/prod-addr',
    type: 2,
    orderNum: 1,
    title: '产品地点',
    icon: 'tag-one',
    anonymous: false,
    name: 'prod-addr',
    component: '/src/views/erp/prod-addr/index.vue',
    keepAlive: true,
    outLink: null,
    createTime: '2024-03-23 10:23:37',
    updateTime: '2024-03-28 09:27:18',
    roles: null
  },
  {
    id: 1,
    parentId: 19,
    path: '/user/page',
    type: 3,
    orderNum: 1,
    title: '分页查询用户',
    icon: null,
    anonymous: false,
    name: null,
    component: null,
    keepAlive: false,
    outLink: null,
    createTime: '2023-05-24 09:16:14',
    updateTime: '2023-05-24 09:16:14',
    roles: null
  },
  {
    id: 57,
    parentId: 41,
    path: '/erp/stock-unlock',
    type: 2,
    orderNum: 1,
    title: '库存解锁',
    icon: 'fish-one',
    anonymous: false,
    name: 'stock-unlock',
    component: '/src/views/erp/stock-unlock/index.vue',
    keepAlive: true,
    outLink: null,
    createTime: '2024-03-23 15:19:32',
    updateTime: '2025-01-10 13:25:47',
    roles: null
  },
  {
    id: 6,
    parentId: 20,
    path: '/role/page',
    type: 3,
    orderNum: 1,
    title: '分页查询角色',
    icon: null,
    anonymous: false,
    name: null,
    component: null,
    keepAlive: false,
    outLink: null,
    createTime: '2023-05-24 09:16:14',
    updateTime: '2023-05-24 09:16:14',
    roles: null
  },
  {
    id: 2,
    parentId: 19,
    path: '/user/save',
    type: 3,
    orderNum: 2,
    title: '添加用户',
    icon: null,
    anonymous: false,
    name: null,
    component: null,
    keepAlive: false,
    outLink: null,
    createTime: '2023-05-24 09:16:14',
    updateTime: '2023-05-24 09:16:14',
    roles: null
  },
  {
    id: 22,
    parentId: 17,
    path: '/system/monitor',
    type: 1,
    orderNum: 2,
    title: '监控管理',
    icon: 'monitor',
    anonymous: false,
    name: '',
    component: null,
    keepAlive: false,
    outLink: null,
    createTime: '2023-05-24 09:16:14',
    updateTime: '2023-05-24 09:16:14',
    roles: null
  },
  {
    id: 60,
    parentId: 63,
    path: '/erp/prod-bps',
    type: 2,
    orderNum: 2,
    title: '产品供应商',
    icon: 'lightning',
    anonymous: false,
    name: 'prod-bps',
    component: '/src/views/erp/prod-bps/index.vue',
    keepAlive: true,
    outLink: null,
    createTime: '2024-03-27 14:25:26',
    updateTime: '2024-03-28 09:27:36',
    roles: null
  },
  {
    id: 71,
    parentId: 41,
    path: '/erp/prod-type',
    type: 2,
    orderNum: 2,
    title: '产品类型',
    icon: 'tag-one',
    anonymous: false,
    name: 'prod-type',
    component: '/src/views/erp/prod-type/index.vue',
    keepAlive: false,
    outLink: null,
    createTime: '2024-07-02 10:43:22',
    updateTime: '2025-01-10 13:26:25',
    roles: null
  },
  {
    id: 17,
    parentId: null,
    path: '/system',
    type: 1,
    orderNum: 2,
    title: '系统管理',
    icon: 'config',
    anonymous: false,
    name: null,
    component: null,
    keepAlive: false,
    outLink: null,
    createTime: '2023-05-24 09:16:14',
    updateTime: '2023-05-24 09:16:14',
    roles: null
  },
  {
    id: 15,
    parentId: 23,
    path: '/system-log/page',
    type: 3,
    orderNum: 2,
    title: '分页查询日志',
    icon: null,
    anonymous: false,
    name: null,
    component: null,
    keepAlive: false,
    outLink: null,
    createTime: '2023-05-24 09:16:14',
    updateTime: '2023-05-24 09:16:14',
    roles: null
  },
  {
    id: 20,
    parentId: 18,
    path: '/system/auth/role',
    type: 2,
    orderNum: 2,
    title: '角色管理',
    icon: 'peoples',
    anonymous: false,
    name: 'role',
    component: '/src/views/system/auth/role/index.vue',
    keepAlive: true,
    outLink: null,
    createTime: '2023-05-24 09:16:14',
    updateTime: '2023-05-24 09:16:14',
    roles: null
  },
  {
    id: 7,
    parentId: 20,
    path: '/role/save',
    type: 3,
    orderNum: 2,
    title: '添加角色',
    icon: null,
    anonymous: false,
    name: null,
    component: null,
    keepAlive: false,
    outLink: null,
    createTime: '2023-05-24 09:16:14',
    updateTime: '2023-05-24 09:16:14',
    roles: null
  },
  {
    id: 21,
    parentId: 18,
    path: '/system/auth/menu',
    type: 2,
    orderNum: 3,
    title: '菜单管理',
    icon: 'system',
    anonymous: false,
    name: 'menu',
    component: '/src/views/system/auth/menu/index.vue',
    keepAlive: false,
    outLink: null,
    createTime: '2023-05-24 09:16:14',
    updateTime: '2023-05-24 09:16:14',
    roles: null
  },
  {
    id: 3,
    parentId: 19,
    path: '/user/update',
    type: 3,
    orderNum: 3,
    title: '修改用户',
    icon: null,
    anonymous: false,
    name: null,
    component: null,
    keepAlive: false,
    outLink: null,
    createTime: '2023-05-24 09:16:14',
    updateTime: '2023-05-24 09:16:14',
    roles: null
  },
  {
    id: 67,
    parentId: 41,
    path: '/erp/stock-capacity',
    type: 2,
    orderNum: 3,
    title: '库存容量',
    icon: 'search',
    anonymous: false,
    name: null,
    component: '/src/views/erp/stock-capacity/index.vue',
    keepAlive: false,
    outLink: null,
    createTime: '2024-05-22 15:20:24',
    updateTime: '2025-01-10 13:26:28',
    roles: null
  },
  {
    id: 69,
    parentId: 63,
    path: '/erp/prod-category',
    type: 2,
    orderNum: 3,
    title: '产品种类',
    icon: 'lightning',
    anonymous: false,
    name: 'prod-category',
    component: '/src/views/erp/prod-category/index.vue',
    keepAlive: true,
    outLink: null,
    createTime: '2024-06-04 11:10:34',
    updateTime: '2024-06-04 11:10:34',
    roles: null
  },
  {
    id: 81,
    parentId: 17,
    path: '/basic-service/push-task',
    type: 2,
    orderNum: 3,
    title: '推送任务',
    icon: 'news',
    anonymous: false,
    name: 'push-task',
    component: '/src/views/system/push-task/index.vue',
    keepAlive: false,
    outLink: null,
    createTime: null,
    updateTime: '2025-01-10 13:20:00',
    roles: null
  },
  {
    id: 8,
    parentId: 20,
    path: '/role/update',
    type: 3,
    orderNum: 3,
    title: '修改角色',
    icon: null,
    anonymous: false,
    name: null,
    component: null,
    keepAlive: false,
    outLink: null,
    createTime: '2023-05-24 09:16:14',
    updateTime: '2023-05-24 09:16:14',
    roles: null
  },
  {
    id: 25,
    parentId: null,
    path: '/visualizing',
    type: 1,
    orderNum: 3,
    title: '数据可视化',
    icon: 'statistic',
    anonymous: false,
    name: '',
    component: null,
    keepAlive: false,
    outLink: null,
    createTime: '2023-05-24 09:16:14',
    updateTime: '2023-05-24 09:16:14',
    roles: null
  },
  {
    id: 16,
    parentId: 23,
    path: '/system-log/clear',
    type: 3,
    orderNum: 3,
    title: '清空日志',
    icon: null,
    anonymous: false,
    name: null,
    component: null,
    keepAlive: false,
    outLink: null,
    createTime: '2023-05-24 09:16:14',
    updateTime: '2023-05-24 09:16:14',
    roles: null
  },
  {
    id: 12,
    parentId: 21,
    path: '/menu/save',
    type: 3,
    orderNum: 4,
    title: '添加菜单',
    icon: null,
    anonymous: false,
    name: null,
    component: null,
    keepAlive: false,
    outLink: null,
    createTime: '2023-05-24 09:16:14',
    updateTime: '2023-05-24 09:16:14',
    roles: null
  },
  {
    id: 9,
    parentId: 20,
    path: '/role/remove',
    type: 3,
    orderNum: 4,
    title: '删除角色',
    icon: null,
    anonymous: false,
    name: null,
    component: null,
    keepAlive: false,
    outLink: null,
    createTime: '2023-05-24 09:16:14',
    updateTime: '2023-05-24 09:16:14',
    roles: null
  },
  {
    id: 79,
    parentId: 17,
    path: '/basic-service/options',
    type: 2,
    orderNum: 4,
    title: '类型选项',
    icon: 'tag-one',
    anonymous: false,
    name: 'options',
    component: '/src/views/system/options/index.vue',
    keepAlive: false,
    outLink: null,
    createTime: null,
    updateTime: '2025-01-10 13:20:05',
    roles: null
  },
  {
    id: 41,
    parentId: null,
    path: '/erp',
    type: 1,
    orderNum: 4,
    title: 'erp系统',
    icon: 'whale',
    anonymous: false,
    name: null,
    component: null,
    keepAlive: false,
    outLink: null,
    createTime: '2023-09-06 09:16:17',
    updateTime: '2024-08-07 10:48:26',
    roles: null
  },
  {
    id: 4,
    parentId: 19,
    path: '/user/updateInfo',
    type: 3,
    orderNum: 4,
    title: '修改个人信息',
    icon: null,
    anonymous: true,
    name: null,
    component: null,
    keepAlive: false,
    outLink: null,
    createTime: '2023-05-24 09:16:14',
    updateTime: '2023-05-24 09:16:14',
    roles: null
  },
  {
    id: 100,
    parentId: 17,
    path: '/system/inform',
    type: 2,
    orderNum: 5,
    title: '通知',
    icon: 'remind',
    anonymous: false,
    name: 'inform',
    component: '/src/views/system/inform/index.vue',
    keepAlive: false,
    outLink: null,
    createTime: null,
    updateTime: '2025-03-22 16:09:37',
    roles: null
  },
  {
    id: 76,
    parentId: 41,
    path: '/erp/transit',
    type: 2,
    orderNum: 5,
    title: '运输提单',
    icon: 'fish-one',
    anonymous: false,
    name: null,
    component: '/src/views/erp/transit/index.vue',
    keepAlive: false,
    outLink: null,
    createTime: null,
    updateTime: '2025-01-10 13:26:03',
    roles: null
  },
  {
    id: 5,
    parentId: 19,
    path: '/user/remove',
    type: 3,
    orderNum: 5,
    title: '删除用户',
    icon: null,
    anonymous: false,
    name: null,
    component: null,
    keepAlive: false,
    outLink: null,
    createTime: '2023-05-24 09:16:14',
    updateTime: '2023-05-24 09:16:14',
    roles: null
  },
  {
    id: 13,
    parentId: 21,
    path: '/menu/update',
    type: 3,
    orderNum: 5,
    title: '修改菜单',
    icon: null,
    anonymous: false,
    name: null,
    component: null,
    keepAlive: false,
    outLink: null,
    createTime: '2023-05-24 09:16:14',
    updateTime: '2023-05-24 09:16:14',
    roles: null
  },
  {
    id: 87,
    parentId: 17,
    path: '/basic-service/options/getTypes/**',
    type: 3,
    orderNum: 6,
    title: '根据模块获取类型选项',
    icon: null,
    anonymous: false,
    name: null,
    component: null,
    keepAlive: false,
    outLink: null,
    createTime: '2025-01-10 13:16:29',
    updateTime: '2025-03-22 16:09:31',
    roles: null
  },
  {
    id: 14,
    parentId: 21,
    path: '/menu/remove',
    type: 3,
    orderNum: 6,
    title: '删除菜单',
    icon: null,
    anonymous: false,
    name: null,
    component: null,
    keepAlive: false,
    outLink: null,
    createTime: '2023-05-24 09:16:14',
    updateTime: '2023-05-24 09:16:14',
    roles: null
  },
  {
    id: 61,
    parentId: 60,
    path: '/erp-service/erp/bpsNumList/**',
    type: 3,
    orderNum: 7,
    title: '获取供应商编码选项',
    icon: null,
    anonymous: false,
    name: null,
    component: null,
    keepAlive: false,
    outLink: null,
    createTime: '2024-03-27 14:27:00',
    updateTime: '2024-03-27 14:30:47',
    roles: null
  },
  {
    id: 59,
    parentId: 41,
    path: '/erp-service/erp/addressList',
    type: 3,
    orderNum: 8,
    title: '产品地点信息接口',
    icon: null,
    anonymous: false,
    name: null,
    component: null,
    keepAlive: false,
    outLink: null,
    createTime: '2024-03-23 16:23:50',
    updateTime: '2025-01-10 13:26:11',
    roles: null
  },
  {
    id: 52,
    parentId: null,
    path: '/form',
    type: 2,
    orderNum: 8,
    title: '表单',
    icon: 'order2',
    anonymous: false,
    name: null,
    component: '/src/views/form/index.vue',
    keepAlive: false,
    outLink: null,
    createTime: '2024-03-20 12:46:14',
    updateTime: '2024-03-20 12:46:29',
    roles: null
  },
  {
    id: 65,
    parentId: null,
    path: '/sale-week-plan',
    type: 2,
    orderNum: 9,
    title: '销售周计划',
    icon: 'log',
    anonymous: false,
    name: null,
    component: '/src/views/sale-week-plan/index.vue',
    keepAlive: false,
    outLink: null,
    createTime: '2024-05-15 14:25:19',
    updateTime: '2024-05-15 14:25:31',
    roles: null
  },
  {
    id: 73,
    parentId: null,
    path: '/asset',
    type: 2,
    orderNum: 10,
    title: '资产清单',
    icon: 'log',
    anonymous: false,
    name: null,
    component: '/src/views/assets/index.vue',
    keepAlive: false,
    outLink: null,
    createTime: '2024-05-15 14:25:19',
    updateTime: '2024-09-06 21:10:02',
    roles: null
  },
  {
    id: 84,
    parentId: null,
    path: '/training-record',
    type: 2,
    orderNum: 12,
    title: '培训记录',
    icon: 'analysis',
    anonymous: false,
    name: '',
    component: '/src/views/training-record/index.vue',
    keepAlive: false,
    outLink: null,
    createTime: null,
    updateTime: '2024-12-28 10:10:41',
    roles: null
  },
  {
    id: 91,
    parentId: null,
    path: '/resManager',
    type: 2,
    orderNum: 13,
    title: '仓储预约',
    icon: 'fish-one',
    anonymous: false,
    name: '',
    component: '/src/views/system/iframe/index.vue',
    keepAlive: false,
    outLink: 'http://eip.supinfood.com/safetyStock/resManager?manager=1',
    createTime: '2025-01-22 11:23:26',
    updateTime: '2025-03-22 17:05:08',
    roles: null
  },
  {
    id: 101,
    parentId: 100,
    path: '/inform/page/**',
    type: 3,
    orderNum: null,
    title: '分页查询通知信息',
    icon: null,
    anonymous: false,
    name: null,
    component: null,
    keepAlive: false,
    outLink: null,
    createTime: null,
    updateTime: null,
    roles: null
  },
  {
    id: 99,
    parentId: 84,
    path: '/data-origin-service/training-record/getByName/**',
    type: 3,
    orderNum: null,
    title: '根据名称查询员工信息',
    icon: null,
    anonymous: false,
    name: null,
    component: null,
    keepAlive: false,
    outLink: null,
    createTime: '2025-03-21 17:14:36',
    updateTime: '2025-03-21 17:14:36',
    roles: null
  },
  {
    id: 102,
    parentId: 108,
    path: '/inform/unreadList/**',
    type: 3,
    orderNum: null,
    title: '查询用户未读通知信息',
    icon: null,
    anonymous: false,
    name: null,
    component: null,
    keepAlive: false,
    outLink: null,
    createTime: null,
    updateTime: '2025-03-22 16:09:06',
    roles: null
  },
  {
    id: 98,
    parentId: 84,
    path: '/data-origin-service/training-record/modelDownload/**',
    type: 3,
    orderNum: null,
    title: '下载培训记录模板',
    icon: null,
    anonymous: false,
    name: null,
    component: null,
    keepAlive: false,
    outLink: null,
    createTime: '2025-03-21 17:14:12',
    updateTime: '2025-03-21 17:14:12',
    roles: null
  },
  {
    id: 103,
    parentId: 100,
    path: '/inform/detail/**',
    type: 3,
    orderNum: null,
    title: '查询通知明细',
    icon: null,
    anonymous: false,
    name: null,
    component: null,
    keepAlive: false,
    outLink: null,
    createTime: null,
    updateTime: null,
    roles: null
  },
  {
    id: 97,
    parentId: 84,
    path: '/data-origin-service/training-record/optionsList/**',
    type: 3,
    orderNum: null,
    title: '获取类型选项',
    icon: null,
    anonymous: false,
    name: null,
    component: null,
    keepAlive: false,
    outLink: null,
    createTime: '2025-03-21 17:13:41',
    updateTime: '2025-03-21 17:13:41',
    roles: null
  },
  {
    id: 96,
    parentId: 84,
    path: '/data-origin-service/training-record/page/**',
    type: 3,
    orderNum: null,
    title: '分页查询培训记录信息',
    icon: null,
    anonymous: false,
    name: null,
    component: null,
    keepAlive: false,
    outLink: null,
    createTime: '2025-03-21 17:12:51',
    updateTime: '2025-03-21 17:12:59',
    roles: null
  },
  {
    id: 104,
    parentId: 100,
    path: '/inform/save/**',
    type: 3,
    orderNum: null,
    title: '添加通知信息',
    icon: null,
    anonymous: false,
    name: null,
    component: null,
    keepAlive: false,
    outLink: null,
    createTime: null,
    updateTime: null,
    roles: null
  },
  {
    id: 95,
    parentId: 84,
    path: '/data-origin-service/training-record/statExport/**',
    type: 3,
    orderNum: null,
    title: '导出培训记录统计信息',
    icon: null,
    anonymous: false,
    name: null,
    component: null,
    keepAlive: false,
    outLink: null,
    createTime: '2025-03-21 17:12:21',
    updateTime: '2025-03-21 17:12:21',
    roles: null
  },
  {
    id: 94,
    parentId: 84,
    path: '/data-origin-service/training-record/statPage/**',
    type: 3,
    orderNum: null,
    title: '分页查询培训记录统计信息',
    icon: null,
    anonymous: false,
    name: null,
    component: null,
    keepAlive: false,
    outLink: null,
    createTime: '2025-03-21 17:11:10',
    updateTime: '2025-03-21 17:11:10',
    roles: null
  },
  {
    id: 105,
    parentId: 100,
    path: '/inform/update/**',
    type: 3,
    orderNum: null,
    title: '修改通知信息',
    icon: null,
    anonymous: false,
    name: null,
    component: null,
    keepAlive: false,
    outLink: null,
    createTime: null,
    updateTime: null,
    roles: null
  },
  {
    id: 106,
    parentId: 100,
    path: '/inform/remove/**',
    type: 3,
    orderNum: null,
    title: '删除通知信息',
    icon: null,
    anonymous: false,
    name: null,
    component: null,
    keepAlive: false,
    outLink: null,
    createTime: null,
    updateTime: null,
    roles: null
  },
  {
    id: 107,
    parentId: 108,
    path: '/inform/markRead/**',
    type: 3,
    orderNum: null,
    title: '添加用户标记已读通知信息',
    icon: null,
    anonymous: false,
    name: null,
    component: null,
    keepAlive: false,
    outLink: null,
    createTime: null,
    updateTime: '2025-03-22 16:09:19',
    roles: null
  },
  {
    id: 108,
    parentId: null,
    path: '/general',
    type: 1,
    orderNum: null,
    title: '通用',
    icon: null,
    anonymous: false,
    name: null,
    component: null,
    keepAlive: false,
    outLink: null,
    createTime: null,
    updateTime: null,
    roles: null
  },
  {
    id: 77,
    parentId: 76,
    path: '/erp-service/transit/**',
    type: 3,
    orderNum: null,
    title: '运输提单接口',
    icon: null,
    anonymous: false,
    name: null,
    component: null,
    keepAlive: false,
    outLink: null,
    createTime: null,
    updateTime: null,
    roles: null
  },
  {
    id: 54,
    parentId: 53,
    path: '/erp-service/erp/batchUpdateProdAddr',
    type: 3,
    orderNum: null,
    title: '产品地点修改',
    icon: null,
    anonymous: false,
    name: null,
    component: null,
    keepAlive: false,
    outLink: null,
    createTime: '2024-03-23 10:24:57',
    updateTime: '2024-03-23 10:24:57',
    roles: null
  },
  {
    id: 58,
    parentId: 57,
    path: '/erp-service/erp/stockUnlock/**',
    type: 3,
    orderNum: null,
    title: '库存解锁接口',
    icon: null,
    anonymous: false,
    name: null,
    component: null,
    keepAlive: false,
    outLink: null,
    createTime: '2024-03-23 15:20:36',
    updateTime: '2024-03-23 15:20:36',
    roles: null
  },
  {
    id: 62,
    parentId: 60,
    path: '/erp-service/erp/saveBatchProdBPS',
    type: 3,
    orderNum: null,
    title: '批量添加产品供应商',
    icon: null,
    anonymous: false,
    name: null,
    component: null,
    keepAlive: false,
    outLink: null,
    createTime: '2024-03-27 14:28:33',
    updateTime: '2024-03-27 14:28:33',
    roles: null
  },
  {
    id: 66,
    parentId: 65,
    path: '/erp-service/saleWeekPlan/**',
    type: 3,
    orderNum: null,
    title: '导入',
    icon: null,
    anonymous: false,
    name: null,
    component: null,
    keepAlive: false,
    outLink: null,
    createTime: '2024-05-15 14:28:36',
    updateTime: '2024-08-19 13:56:37',
    roles: null
  },
  {
    id: 68,
    parentId: 67,
    path: '/erp-service/stock-capacity/**',
    type: 3,
    orderNum: null,
    title: '库存容量接口',
    icon: null,
    anonymous: false,
    name: null,
    component: null,
    keepAlive: false,
    outLink: null,
    createTime: '2024-05-24 10:18:21',
    updateTime: '2025-01-10 11:28:25',
    roles: null
  },
  {
    id: 70,
    parentId: 69,
    path: '/erp-service/erp/updateProdType',
    type: 3,
    orderNum: null,
    title: '产品种类修改',
    icon: null,
    anonymous: false,
    name: null,
    component: null,
    keepAlive: false,
    outLink: null,
    createTime: '2024-06-04 11:11:18',
    updateTime: '2024-06-04 11:11:18',
    roles: null
  },
  {
    id: 72,
    parentId: 71,
    path: '/erp-service/prodType/**',
    type: 3,
    orderNum: null,
    title: '产品类型接口',
    icon: null,
    anonymous: false,
    name: null,
    component: null,
    keepAlive: false,
    outLink: null,
    createTime: '2024-07-02 10:43:28',
    updateTime: '2025-01-10 11:29:27',
    roles: null
  },
  {
    id: 75,
    parentId: 73,
    path: '/basic-service/assets/**',
    type: 3,
    orderNum: null,
    title: '资产清单接口',
    icon: null,
    anonymous: false,
    name: null,
    component: null,
    keepAlive: false,
    outLink: null,
    createTime: '2024-07-02 10:43:28',
    updateTime: '2024-10-18 17:19:37',
    roles: null
  },
  {
    id: 90,
    parentId: 92,
    path: '/erp/financial',
    type: 2,
    orderNum: null,
    title: '销售经营报表',
    icon: 'ranking',
    anonymous: false,
    name: '',
    component: '/src/views/system/iframe/index.vue',
    keepAlive: false,
    outLink: 'http://180.100.207.79:6080/financial/home',
    createTime: '2025-01-22 10:56:16',
    updateTime: '2025-02-20 16:39:01',
    roles: null
  },
  {
    id: 78,
    parentId: 41,
    path: '/erp-service/options/**',
    type: 3,
    orderNum: null,
    title: 'erp菜单选项接口',
    icon: null,
    anonymous: false,
    name: null,
    component: null,
    keepAlive: false,
    outLink: null,
    createTime: null,
    updateTime: null,
    roles: null
  },
  {
    id: 80,
    parentId: 79,
    path: '/basic-service/options/**',
    type: 3,
    orderNum: null,
    title: '类型选项接口',
    icon: null,
    anonymous: false,
    name: null,
    component: null,
    keepAlive: false,
    outLink: null,
    createTime: null,
    updateTime: null,
    roles: null
  },
  {
    id: 82,
    parentId: 81,
    path: '/basic-service/push-task/**',
    type: 3,
    orderNum: null,
    title: '推送任务接口',
    icon: null,
    anonymous: false,
    name: null,
    component: null,
    keepAlive: false,
    outLink: null,
    createTime: null,
    updateTime: null,
    roles: null
  },
  {
    id: 83,
    parentId: 23,
    path: '/system-log/getTypes',
    type: 3,
    orderNum: null,
    title: '日志类型选项',
    icon: null,
    anonymous: false,
    name: null,
    component: null,
    keepAlive: false,
    outLink: null,
    createTime: '2024-10-31 09:17:52',
    updateTime: '2024-10-31 09:18:05',
    roles: null
  },
  {
    id: 85,
    parentId: 84,
    path: '/data-origin-service/training-record/**',
    type: 3,
    orderNum: null,
    title: '培训记录接口',
    icon: null,
    anonymous: false,
    name: null,
    component: null,
    keepAlive: false,
    outLink: null,
    createTime: null,
    updateTime: '2024-12-28 09:20:44',
    roles: null
  },
  {
    id: 86,
    parentId: 41,
    path: '/erp-service/erp/optionsList/**',
    type: 3,
    orderNum: null,
    title: '获取erp类型选项',
    icon: null,
    anonymous: false,
    name: null,
    component: null,
    keepAlive: false,
    outLink: null,
    createTime: '2025-01-08 15:52:09',
    updateTime: '2025-01-10 11:31:45',
    roles: null
  },
  {
    id: 88,
    parentId: 41,
    path: '/system/iframe',
    type: 2,
    orderNum: null,
    title: '外链',
    icon: 'share',
    anonymous: false,
    name: '',
    component: '/src/views/system/iframe/index.vue',
    keepAlive: false,
    outLink: 'https://leetcode.cn',
    createTime: '2025-01-16 14:45:08',
    updateTime: '2025-01-16 15:11:23',
    roles: null
  },
  {
    id: 89,
    parentId: 92,
    path: '/erp/nbpc-sales',
    type: 2,
    orderNum: null,
    title: '非大客户销售报表',
    icon: 'statistic',
    anonymous: false,
    name: '',
    component: '/src/views/system/iframe/index.vue',
    keepAlive: false,
    outLink: 'http://180.100.207.79:6080/financial/notBigCust',
    createTime: '2025-01-21 14:39:56',
    updateTime: '2025-02-20 17:13:41',
    roles: null
  }
]

const states = [
  'Alabama',
  'Alaska',
  'Arizona',
  'Arkansas',
  'California',
  'Colorado',
  'Connecticut',
  'Delaware',
  'Florida',
  'Georgia',
  'Hawaii',
  'Idaho',
  'Illinois',
  'Indiana',
  'Iowa',
  'Kansas',
  'Kentucky',
  'Louisiana',
  'Maine',
  'Maryland',
  'Massachusetts',
  'Michigan',
  'Minnesota',
  'Mississippi',
  'Missouri',
  'Montana',
  'Nebraska',
  'Nevada',
  'New Hampshire',
  'New Jersey',
  'New Mexico',
  'New York',
  'North Carolina',
  'North Dakota',
  'Ohio',
  'Oklahoma',
  'Oregon',
  'Pennsylvania',
  'Rhode Island',
  'South Carolina',
  'South Dakota',
  'Tennessee',
  'Texas',
  'Utah',
  'Vermont',
  'Virginia',
  'Washington',
  'West Virginia',
  'Wisconsin',
  'Wyoming'
]

function toOptions(menu: any[]) {
  if (isEmpty(menu)) return menu
  let arr = menu.filter(e => e.type != 3)
  let options = new Array()
  function rootNode(val: any) {
    if (isEmpty(val) || val.parentId == null) {
      return val
    }
    // debugger
    let o = arr.find(e => e.id == val.parentId)

    return rootNode(o)
  }
  arr.forEach(e => {
    if (e.type != 1) {
      let root = rootNode(e)
      if (e.parentId == null) {
        options.push({ value: e.title, path: e.path })
      } else {
        options.push({ value: `${root.title}>${e.title}`, path: e.path })
      }
    }
  })
  return options
}
let options = toOptions(menu)
console.log(options)

function remoteSearch(val: string, done: (arg: any[]) => void) {
  if (val == '') {
    done([])
    return
  }
  setTimeout(() => {
    // done(states.filter(e => e.toLowerCase().includes(val.toLowerCase())))
    let arr = options.filter(e => e.value.includes(val) || e.path.includes(val))
    console.log(arr, val)
    done(arr)
    console.log('keyword:', keyword.value)
  }, 200)
}

function searchBtn() {
  show.value = true
  searchRef.value.focus()
}

function select(val: any) {
  keyword.value = ''
  searchRef.value.blur()
}

</script>

<style lang="scss" scoped>
.search {
  display: flex;
  align-items: center;
  .icon {
    line-height: 32px;
  }
  .input-box {
    width: 0;
    overflow: hidden;
    transition: all 0.2s ease-in-out;
  }
  .show {
    width: 200px;
    margin-left: 10px;
  }
}
</style>
