export * from './anchor';
export * from './chat';
export * from './comment';
export * from './comment-nav';
export * from './comment-scroll';
export * from './counter';
export * from './dialog';
export * from './divider';
export * from './editor';
export * from './emoji';
export * from './fold';
export * from './icon';
export * from './notice-bar';
export * from './search';
export * from './toast';
import { App } from 'vue';
declare const install: (app: App) => void;
export { install };
